name: Deploy moxai.ru

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.REMOTE_HOST }}
      USERNAME: ${{ secrets.REMOTE_USER }}
      KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_PATH: ${{ secrets.REMOTE_PATH }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Install Backend dependencies
        working-directory: backend
        run: |
          npm ci

      - name: Clear Remote Directories
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          script: |
            rm -rf ${{ env.REMOTE_PATH }}/frontend/*
            rm -rf ${{ env.REMOTE_PATH }}/backend/*

      - name: Deploy Frontend Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          source: "./frontend/dist/*"
          target: "${{ env.REMOTE_PATH }}/frontend/"
          strip_components: 2

      - name: Deploy Backend Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          source: "./backend/*"
          target: "${{ env.REMOTE_PATH }}/backend/"
          strip_components: 1

      - name: Update Backend environment file
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          script: |
            rm -f ${{ env.REMOTE_PATH }}/backend/.env
            echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > ${{ env.REMOTE_PATH }}/backend/.env
            echo "TELEGRAM_CHAT_IDS=${{ secrets.TELEGRAM_CHAT_IDS }}" >> ${{ env.REMOTE_PATH }}/backend/.env

      - name: Restart Backend Service
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          script: sudo systemctl restart moxai_ru_backend.service
