name: Deploy moxai.ru

on:
  push:
    branches:
      - test-github-actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Clear previous builds
        uses: appleboy/ssh-action@v1.2.2
        env:
          WORKDIR_PATH: ${{ secrets.REMOTE_PATH }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: WORKDIR_PATH
          script: |
            rm -rf $WORKDIR_PATH/backend
            rm -rf $WORKDIR_PATH/frontend

      - name: Build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Build backend
        working-directory: ./backend
        run: |
          npm ci

      - name: Copy frontend to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./frontend/dist/*"
          target: ${{ secrets.REMOTE_PATH }}
          strip_components: 1

      - name: Copy backend to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./backend/*"
          target: ${{ secrets.REMOTE_PATH }}

      - name: Deploy backend
        uses: appleboy/ssh-action@v1.2.2
        env:
          WORKDIR_PATH: ${{ secrets.REMOTE_PATH }}
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: WORKDIR_PATH
          script: |
            mv $WORKDIR_PATH/dist $WORKDIR_PATH/frontend
            systemctl restart moxai_ru_backend.service

      # - name: Install SSH client
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y openssh-client

      # - name: Execute test command on remote server
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
      #   run: |
      #     # Сохранение приватного ключа в файл
      #     echo "$SSH_PRIVATE_KEY" > private_key
      #     chmod 600 private_key

      #     # Выполнение SSH-команды на удалённом сервере:
      #     # Здесь создаётся или перезаписывается файл test.txt с тестовым сообщением,
      #     # содержащим текущую дату и время.
      #     ssh -i private_key -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "echo 'Test deployment triggered at $(date)' > $REMOTE_PATH/test.txt"

      #     # Удаление временного файла с ключом
      #     rm private_key
